### ISSUE TITLE
Penamaan Komponen Kustom

### ISSUE THREAD

**Issue by jefrydco** [Lucky7Tb/VueFundamentalHimitpens#1]
Hi Mas Lucky, terima kasih sudah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Mukti. Saya ada satu saran Mas untuk kode yg Mas kirimkan.

Luar biasa Mas, Mas sudah menerapkan penggunaan kustom komponen pada kode yg Mas kirimkan. Pada baris pertama pada berkas `app.js` berikut https://github.com/Lucky7Tb/Vue-Fundamental-Himitpens/blob/master/js/app.js#L1 Mas memberikan nama komponennya `card`.

Namun saya saranakan untuk penamaan komponen tersebut agar menggunakan prefiks tertentu Mas. Katakanlah `my-card` atau `app-card`. Beberapa tujuannya antara lain:

1. Agar tidak terjadi konflik antara tag HTML dan komponen kustom yang telah kita buat. Mungkin sekarang `card` bukan merupakan tag HTML, namun katakanlah di masa depan terdapat penambahan tag HTML baru dengan nama `card`. Sehingga kustom komponen yg Mas buat bisa jadi oleh Vue.js ditampilkan menjadi tag HTML saja.
2. Agar memudahkan pencarian. Jika kita ingin mencari komponen kustom yang telah kita buat. Kita bisa mencarinya menggunakan prefiks tersebut.

Vue.js juga telah membuat serangkaian kaidah penulisan penamaan komponen yg disarankan. Lebih lanjut Mas dapat membacanya pada tautan berikut, [Vue.js Style Guide - Single-instance component names](https://vuejs.org/v2/style-guide/#Single-instance-component-names-strongly-recommended)

Semangat Mas! 😄

**Comment by Lucky7Tb** [comment]
Wih makasih kak udah dikasih saran buat best practice nya🙏🙏 semangat terus kak jefry buat sharing dan ngajar vue js lagi🙏🙏
